# Array

---
#### memo
`export CONDA_SHLVL=0`

<img src="numpy_dtypes.png">

In [33]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5], dtype=int)
print("The given array is :\n",arr)
print("The size of array arr is:",arr.size)
print("The memorysize of each element of arr is:", arr.itemsize,"bytes")
print("The memory size of numpy array arr is:",arr.itemsize*arr.size,"bytes")
print("- - "*20)

arr1 = np.array([1, 2, 3, 4, 5], dtype="int64")
print("The given array is :\n",arr1)
print("The size of array arr is:",arr1.size)
print("The memorysize of each element of arr is:", arr1.itemsize,"bytes")
print("The memory size of numpy array arr is:",arr1.itemsize*arr1.size,"bytes")

The given array is :
 [1 2 3 4 5]
The size of array arr is: 5
The memorysize of each element of arr is: 8 bytes
The memory size of numpy array arr is: 40 bytes
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
The given array is :
 [1 2 3 4 5]
The size of array arr is: 5
The memorysize of each element of arr is: 8 bytes
The memory size of numpy array arr is: 40 bytes


### 2D Array

In [60]:
import numpy as np

np.random.seed(0)
arr2D = np.array( np.random.randint(1,100, size=(4,3)), dtype=int)
print("The given 2D array is :\n",arr2D)
print( "The size of 2D array arr2D is:",arr2D.size)
print("The memorysize of each element of arr2D is:", arr2D.itemsize,"bytes")
print("The memory size of numpy array arr2D is:",arr2D.itemsize*arr2D.size,"bytes")
print( arr2D[:, 2] )
print( arr2D[1, :] )

The given 2D array is :
 [[45 48 65]
 [68 68 10]
 [84 22 37]
 [88 71 89]]
The size of 2D array arr2D is: 12
The memorysize of each element of arr2D is: 8 bytes
The memory size of numpy array arr2D is: 96 bytes
[65 10 37 89]
10
