# Array

---
#### memo
`export CONDA_SHLVL=0`

<img src="numpy_dtypes.png">

In [33]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5], dtype=int)
print("The given array is :\n",arr)
print("The size of array arr is:",arr.size)
print("The memorysize of each element of arr is:", arr.itemsize,"bytes")
print("The memory size of numpy array arr is:",arr.itemsize*arr.size,"bytes")
print("- - "*20)

arr1 = np.array([1, 2, 3, 4, 5], dtype="int64")
print("The given array is :\n",arr1)
print("The size of array arr is:",arr1.size)
print("The memorysize of each element of arr is:", arr1.itemsize,"bytes")
print("The memory size of numpy array arr is:",arr1.itemsize*arr1.size,"bytes")

The given array is :
 [1 2 3 4 5]
The size of array arr is: 5
The memorysize of each element of arr is: 8 bytes
The memory size of numpy array arr is: 40 bytes
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
The given array is :
 [1 2 3 4 5]
The size of array arr is: 5
The memorysize of each element of arr is: 8 bytes
The memory size of numpy array arr is: 40 bytes


### 2D Array

In [61]:
import numpy as np

np.random.seed(0)
arr2D = np.array( np.random.randint(1,100, size=(4,3)), dtype=int)
print("The given 2D array is :\n",arr2D)
print( "The size of 2D array arr2D is:",arr2D.size)
print("The memorysize of each element of arr2D is:", arr2D.itemsize,"bytes")
print("The memory size of numpy array arr2D is:",arr2D.itemsize*arr2D.size,"bytes")
print( arr2D[:, 2] )
print( arr2D[1, :] )

The given 2D array is :
 [[45 48 65]
 [68 68 10]
 [84 22 37]
 [88 71 89]]
The size of 2D array arr2D is: 12
The memorysize of each element of arr2D is: 8 bytes
The memory size of numpy array arr2D is: 96 bytes
[65 10 37 89]
[68 68 10]


### 3D Array

In [64]:
import numpy as np

np.random.seed(0)
arr3D = np.array( np.random.randint(1,100, size=(3, 4, 5)), dtype=int)
arr3D

array([[[45, 48, 65, 68, 68],
        [10, 84, 22, 37, 88],
        [71, 89, 89, 13, 59],
        [66, 40, 88, 47, 89]],

       [[82, 38, 26, 78, 73],
        [10, 21, 81, 70, 80],
        [48, 65, 83, 89, 50],
        [30, 20, 20, 15, 40]],

       [[33, 66, 10, 58, 33],
        [32, 75, 24, 36, 76],
        [56, 29, 35,  1,  1],
        [37, 54,  6, 39, 18]]])

### 4D Array

In [65]:
import numpy as np

np.random.seed(0)
arr4D = np.array( np.random.randint(1,100, size=(2, 3, 4, 5)), dtype=int)
arr4D

array([[[[45, 48, 65, 68, 68],
         [10, 84, 22, 37, 88],
         [71, 89, 89, 13, 59],
         [66, 40, 88, 47, 89]],

        [[82, 38, 26, 78, 73],
         [10, 21, 81, 70, 80],
         [48, 65, 83, 89, 50],
         [30, 20, 20, 15, 40]],

        [[33, 66, 10, 58, 33],
         [32, 75, 24, 36, 76],
         [56, 29, 35,  1,  1],
         [37, 54,  6, 39, 18]]],


       [[[80,  5, 43, 59, 32],
         [ 2, 66, 42, 58, 36],
         [12, 47, 83, 92,  1],
         [15, 54, 13, 43, 85]],

        [[76, 69,  7, 69, 48],
         [ 4, 77, 53, 79, 16],
         [21, 59, 24, 80, 14],
         [86, 49, 50, 70, 42]],

        [[36, 65, 96, 70, 95],
         [ 1, 51, 37, 35, 49],
         [94,  4, 99, 43, 78],
         [22, 74,  1, 11, 44]]]])

## Using Python list to form 1D list

In [71]:
import numpy as np

np.random.seed(0)
lst1D = [ np.random.randint(1, 101) for i in range(5) ]
lst1D

[45, 48, 65, 68, 68]

### 2D list

In [90]:
import numpy as np

lst2D = [ None ] * 5
np.random.seed(0)
for i in range(5):
    lst2D[i] = [ np.random.randint(1, 101) for j in range(4) ]
lst2D
# print(lst2D)
# lst2D[1, 0]

[[45, 48, 65, 68],
 [68, 10, 84, 22],
 [37, 88, 71, 89],
 [89, 13, 59, 66],
 [40, 88, 47, 89]]

In [97]:
import numpy as np

lst2D = [ None ] * 5
np.random.seed(0)
for i in range(5):
    lst2D[i] = [ np.random.randint(1, 101) for j in range(4) ]
lst2D[1][:]

[68, 10, 84, 22]

In [100]:
import numpy as np

lst2D = [ None ] * 5
np.random.seed(0)
for i in range(5):
    lst2D[i] = [ np.random.randint(1, 101) for j in range(4) ]
lst2D[:][1]

[68, 10, 84, 22]

In [101]:
import numpy as np

lst2D = [ None ] * 5
np.random.seed(0)
for i in range(5):
    lst2D[i] = [ np.random.randint(1, 101) for j in range(4) ]
lst2D[:, 1]

TypeError: list indices must be integers or slices, not tuple

In [102]:
import numpy as np

lst2D = [ None ] * 5
np.random.seed(0)
for i in range(5):
    lst2D[i] = [ np.random.randint(1, 101) for j in range(4) ]
lst2D[1, :]

TypeError: list indices must be integers or slices, not tuple