# Matrix (矩陣)

### 2 個 Matrix 的 加法 (Addition) 與 減法 (Subtraction) 運算
運算時是以矩陣相對應位置的元素進行運算，所以這 2 個矩陣彼此的 row 與 column 必須相同。

In [7]:
import numpy as np

np.random.seed(0) # seed for reproducibility
matrix_A = np.random.randint(0, 10, (4, 6)) # 4x6 matrix with random integers between 0 and 10
matrix_B = np.random.randint(0, 10, (4, 6)) # 4x6 matrix with random integers between 0 and 10
print( f"matrix_A: \n{matrix_A}") # print matrix_A
print( f"\nmatrix_B: \n{matrix_B}") # print matrix_B
matrix_C = matrix_A + matrix_B # add matrix_A and matrix_B
matrix_D = matrix_A - matrix_B # subtract matrix_A and matrix_B
print( f"\nmatrix_A + matrix_B: \n{matrix_C}") # print the sum of matrix_A and matrix_B
print( f"\nmatrix_A - matrix_B: \n{matrix_D}") # print the difference of matrix_A and matrix_B

matrix_A: 
[[5 0 3 3 7 9]
 [3 5 2 4 7 6]
 [8 8 1 6 7 7]
 [8 1 5 9 8 9]]

matrix_B: 
[[4 3 0 3 5 0]
 [2 3 8 1 3 3]
 [3 7 0 1 9 9]
 [0 4 7 3 2 7]]

matrix_A + matrix_B: 
[[ 9  3  3  6 12  9]
 [ 5  8 10  5 10  9]
 [11 15  1  7 16 16]
 [ 8  5 12 12 10 16]]

matrix_A * matrix_B: 
[[20  0  0  9 35  0]
 [ 6 15 16  4 21 18]
 [24 56  0  6 63 63]
 [ 0  4 35 27 16 63]]


## 矩陣乘法 (Multiplication)

### Hadamard Product
如果第一個矩陣的列數與第二個矩陣的行數相等，則兩個矩陣可以進行相乘。

$$C[i][j] = A[i][j] \times B[i][j]$$

- **條件**：兩個矩陣必須具有相同的維度。
- **複雜度**：對於兩個 $n \times n$ 矩陣，時間複雜度為 $O(n^2)$。

In [8]:
import numpy as np

np.random.seed(0) # seed for reproducibility
matrix_A = np.random.randint(0, 10, (4, 6)) 
matrix_B = np.random.randint(0, 10, (4, 6)) 
matrix_AB = matrix_A * matrix_B # element-wise multiplication of matrix_A and matrix_B
print( f"matrix_A: \n{matrix_A}") # print matrix_A
print( f"\nmatrix_B: \n{matrix_B}") # print matrix_B
print( f"\nmatrix_A * matrix_B: \n{matrix_AB}") # print matrix_AB

matrix_A: 
[[5 0 3 3 7 9]
 [3 5 2 4 7 6]
 [8 8 1 6 7 7]
 [8 1 5 9 8 9]]

matrix_B: 
[[4 3 0 3 5 0]
 [2 3 8 1 3 3]
 [3 7 0 1 9 9]
 [0 4 7 3 2 7]]

matrix_A * matrix_B: 
[[20  0  0  9 35  0]
 [ 6 15 16  4 21 18]
 [24 56  0  6 63 63]
 [ 0  4 35 27 16 63]]
