# Matrix (矩陣)

### 2 個 Matrix 的 加法 (Addition) 與 減法 (Subtraction) 運算
運算時是以矩陣相對應位置的元素進行運算，所以這 2 個矩陣彼此的 row 與 column 必須相同。

In [2]:
import numpy as np

np.random.seed(0) # seed for reproducibility
matrix_A = np.random.randint(0, 10, (4, 6)) # 4x6 matrix with random integers between 0 and 10
matrix_B = np.random.randint(0, 10, (4, 6)) # 4x6 matrix with random integers between 0 and 10
print( f"matrix_A: \n{matrix_A}") # print matrix_A
print( f"\nmatrix_B: \n{matrix_B}") # print matrix_B
matrix_C = matrix_A + matrix_B # add matrix_A and matrix_B
matrix_D = matrix_A - matrix_B # subtract matrix_A and matrix_B
print( f"\nmatrix_A + matrix_B: \n{matrix_C}") # print the sum of matrix_A and matrix_B
print( f"\nmatrix_A - matrix_B: \n{matrix_D}") # print the difference of matrix_A and matrix_B

matrix_A: 
[[5 0 3 3 7 9]
 [3 5 2 4 7 6]
 [8 8 1 6 7 7]
 [8 1 5 9 8 9]]

matrix_B: 
[[4 3 0 3 5 0]
 [2 3 8 1 3 3]
 [3 7 0 1 9 9]
 [0 4 7 3 2 7]]

matrix_A + matrix_B: 
[[ 9  3  3  6 12  9]
 [ 5  8 10  5 10  9]
 [11 15  1  7 16 16]
 [ 8  5 12 12 10 16]]

matrix_A - matrix_B: 
[[ 1 -3  3  0  2  9]
 [ 1  2 -6  3  4  3]
 [ 5  1  1  5 -2 -2]
 [ 8 -3 -2  6  6  2]]


## 矩陣乘法 (Multiplication)

### Hadamard Product
如果第一個矩陣的列數與第二個矩陣的行數相等，則兩個矩陣可以進行相乘。

$$C[i][j] = A[i][j] \times B[i][j]$$

- **條件**：兩個矩陣必須具有相同的維度。
- **複雜度**：對於兩個 $n \times n$ 矩陣，時間複雜度為 $O(n^2)$。

In [8]:
import numpy as np

np.random.seed(0) # seed for reproducibility
matrix_A = np.random.randint(0, 10, (4, 6)) 
matrix_B = np.random.randint(0, 10, (4, 6)) 
matrix_AB = matrix_A * matrix_B # element-wise multiplication of matrix_A and matrix_B
print( f"matrix_A: \n{matrix_A}") # print matrix_A
print( f"\nmatrix_B: \n{matrix_B}") # print matrix_B
print( f"\nmatrix_A * matrix_B: \n{matrix_AB}") # print matrix_AB

matrix_A: 
[[5 0 3 3 7 9]
 [3 5 2 4 7 6]
 [8 8 1 6 7 7]
 [8 1 5 9 8 9]]

matrix_B: 
[[4 3 0 3 5 0]
 [2 3 8 1 3 3]
 [3 7 0 1 9 9]
 [0 4 7 3 2 7]]

matrix_A * matrix_B: 
[[20  0  0  9 35  0]
 [ 6 15 16  4 21 18]
 [24 56  0  6 63 63]
 [ 0  4 35 27 16 63]]


## 內積/點積 (Dot production)

內積是一種專門用於向量 (Vector) 的矩陣乘法，結果是一個純量 (scalar)，而非矩陣或向量。

- **操作**：給定兩個相同長度的向量 $\mathbf{a}$ 和 $\mathbf{b}$，點積的計算方式如下：

$$\mathbf{a} \cdot \mathbf{b} = \sum_{i=1}^{n} a_i \times b_i$$

  其中 $a_i$ 和 $b_i$ 是向量 $\mathbf{a}$ 和 $\mathbf{b}$ 的各個分量。

- **結果**：點積的結果是一個標量值。
- **範例**：如果 $\mathbf{a} = [1, 2, 3]$ 和 $\mathbf{b} = [4, 5, 6]$，則點積為：

$$\mathbf{a} \cdot \mathbf{b} = (1 \times 4) + (2 \times 5) + (3 \times 6) = 32$$

- **幾何意義**：點積反映了一個向量在另一個向量方向上的延伸量，它與兩向量之間的夾角的餘弦相關：

$$\mathbf{a} \cdot \mathbf{b} = |\mathbf{a}| |\mathbf{b}| \cos(\theta)$$
  其中 $\theta$ 是向量 $\mathbf{a}$ 和 $\mathbf{b}$ 之間的夾角。

##### Example
- **Input Vectors**:
  - $a = [1, 2, 3]$
  - $b = [4, 5, 6]$
- **Dot Product**:
  $$a \cdot b = (1 \times 4) + (2 \times 5) + (3 \times 6) = 32$$

In [3]:
import numpy as np

# Define two vectors a and b
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Compute the dot product
dot_product = np.dot(a, b)

# Print the result
print( f"Dot product of vectors a and b: {dot_product}")

Dot product of vectors a and b: 32


#### Dot production for two matrices
- **Input Matrices**:
  - $A$ is a $4\times3$ matrix.
  - $B$ is a $3\times4$ matrix.
- **Dot Product**: The `np.dot()` function computes the matrix product (dot product) of $A$ and $B$.

In [13]:
import numpy as np

# Define two matrices A and B
A = np.array( [ [1, 2, 3],
                [4, 5, 6],
                [7, 8, 9],
                [2, 1, 2]] )

B = np.array( [ [9, 8, 7, 1],
                [6, 5, 4, 4],
                [3, 2, 1, 5] ] )

# Compute the dot product
dot_product = np.dot(A, B)

# Print the result
print("Dot product of matrices A and B:")
print(dot_product)

Dot product of matrices A and B:
[[ 30  24  18  24]
 [ 84  69  54  54]
 [138 114  90  84]
 [ 30  25  20  16]]
