In [7]:
import numpy as np

np.random.seed(0)
matrix_A = np.random.randint(0, 10, (4, 6))
matrix_B = np.random.randint(0, 10, (4, 6))
print( f"matrix_A: \n{matrix_A}")
print( f"\nmatrix_B: \n{matrix_B}")
matrix_C = matrix_A + matrix_B
matrix_D = matrix_A * matrix_B
print( f"\nmatrix_A + matrix_B: \n{matrix_C}")
print( f"\nmatrix_A * matrix_B: \n{matrix_D}")

matrix_A: 
[[5 0 3 3 7 9]
 [3 5 2 4 7 6]
 [8 8 1 6 7 7]
 [8 1 5 9 8 9]]

matrix_B: 
[[4 3 0 3 5 0]
 [2 3 8 1 3 3]
 [3 7 0 1 9 9]
 [0 4 7 3 2 7]]

matrix_A + matrix_B: 
[[ 9  3  3  6 12  9]
 [ 5  8 10  5 10  9]
 [11 15  1  7 16 16]
 [ 8  5 12 12 10 16]]

matrix_A * matrix_B: 
[[20  0  0  9 35  0]
 [ 6 15 16  4 21 18]
 [24 56  0  6 63 63]
 [ 0  4 35 27 16 63]]
